/* ============================================================
   CORPUS BUILDER FOR ORE TO ACTION
   Generates stations.json, edges.json, and companies.json
   strictly inside /Users/kanku/Desktop/Projects/robotics
   ============================================================ */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const D = path.join(ROOT, "data/static");

import { S01_S06 } from "./data-part1.mjs";
import { S07_S14 } from "./data-part2.mjs";
import { S15_S21 } from "./data-part3.mjs";
import { S22_S27 } from "./data-part4.mjs";

const ALL_STATIONS = [
  ...S01_S06,
  ...S07_S14,
  ...S15_S21,
  ...S22_S27
];

console.log(`Assembled ${ALL_STATIONS.length} total stations.`);

// Map of station IDs for quick validation
const stationIdSet = new Set(ALL_STATIONS.map(s => s.i));

// Define upstream DAG edges for all stations
// Key = Downstream Station ID, Value = Array of Upstream Station IDs
const EDGES = {
  // Stratum 01: Lithosphere (root nodes: no upstream edges)
  ndpr: [],
  heavyre: [],
  li: [],
  cu: [],
  feal: [],
  graphite: [],

  // Stratum 02: Feedstock
  ndfeb: ["ndpr", "heavyre"],
  smco: ["heavyre", "cu"],
  cathode: ["li"],
  steels: ["feal"],
  polymers: ["feal"],
  lube: ["feal"],

  // Stratum 03: Stock
  billet: ["feal"],
  cfrp: ["polymers"],
  castings: ["feal"],
  powder: ["feal", "billet"],

  // Stratum 04: Fabrication
  grind: ["steels", "billet"],
  hobbing: ["steels", "billet"],
  hardturn: ["steels", "billet"],
  mim: ["powder", "polymers"],
  am: ["powder"],
  metrol: ["grind", "hardturn"],

  // Stratum 05: Bearings & Guides
  xroller: ["steels", "grind", "lube"],
  linrail: ["steels", "grind", "lube"],
  ballscrew: ["steels", "grind", "hardturn"],
  bushings: ["polymers", "steels"],

  // Stratum 06: Transmission
  strainwave: ["steels", "hobbing", "grind", "xroller", "lube"],
  cycloid: ["steels", "grind", "xroller", "lube"],
  planetary: ["steels", "hobbing", "grind", "lube"],
  qdd: ["planetary", "steels"],
  tendon: ["cfrp", "polymers", "steels"],
  linact: ["ballscrew", "steels", "grind"],

  // Stratum 07: Motor
  frameless: ["ndfeb", "cu", "steels", "windings", "magassy"],
  torquemotor: ["ndfeb", "cu", "steels", "windings"],
  servo: ["frameless", "magassy", "windings"],
  magassy: ["ndfeb", "smco", "steels"],
  windings: ["cu", "polymers"],

  // Stratum 08: Actuation
  jointmod: ["frameless", "strainwave", "drives", "brakes", "encoders"],
  drives: ["edgesoc", "mcu", "currentsense"],
  brakes: ["steels", "cu", "polymers"],
  sea: ["jointmod", "steels", "encoders"],
  fluidic: ["steels", "hardturn", "lube"],
  thermact: ["cu", "billet", "polymers"],

  // Stratum 09: Proprioception
  encoders: ["metrol", "polymers"],
  resolver: ["cu", "steels", "windings"],
  imu: ["metrol"],
  jts: ["steels", "metrol"],
  currentsense: ["cu"],

  // Stratum 10: Exteroception
  cam: ["metrol"],
  depth: ["cam", "metrol"],
  lidar: ["cam", "metrol"],
  radar: ["metrol"],
  tactile: ["cam", "polymers", "jts"],
  event: ["cam", "metrol"],

  // Stratum 11: Compute
  edgesoc: [],
  mcu: [],
  robomodule: ["edgesoc", "mcu", "determinism"],
  traincompute: [], // Boundary station: explicitly declared []
  determinism: ["mcu"],

  // Stratum 12: Power
  cells: ["cathode", "graphite", "cu"],
  pack: ["cells", "mcu", "thermact"],
  powerstage: ["cu", "mcu"],
  tether: ["cu", "polymers"],
  dock: ["pack", "powerstage", "cu"],

  // Stratum 13: Chassis & End-Effector
  links: ["billet", "cfrp", "castings", "am", "hardturn"],
  gripper: ["jointmod", "tendon", "links", "tactile", "mcu"],
  hand: ["mim", "tendon", "frameless", "tactile", "encoders", "mcu"],
  toolchange: ["steels", "hardturn", "safetyio"],
  cabling: ["cu", "polymers", "tether"],
  ingress: ["polymers", "bushings"],

  // Stratum 14: Assembly
  cm: ["links", "jointmod", "robomodule", "pack", "cabling", "ingress"],
  harness: ["cu", "cabling", "polymers"],
  calib: ["cm", "metrol", "encoders", "imu"],
  secondsource: ["cm", "strainwave", "frameless", "xroller"],

  // Stratum 15: Firmware & Real-time
  currentloop: ["mcu", "drives"],
  fieldbus: ["mcu", "determinism", "currentloop"],
  rtos: ["mcu", "edgesoc"],
  safetyio: ["mcu", "fieldbus", "brakes"],
  otafw: ["mcu", "fieldbus", "rtos"],

  // Stratum 16: Middleware
  ros: ["rtos", "robomodule"],
  zenoh: ["rtos", "fieldbus"],
  drivers: ["ros", "fieldbus", "calib"],
  logging: ["ros", "zenoh"],
  bt: ["ros", "drivers"],

  // Stratum 17: Control
  kine: ["drivers", "calib"],
  dyn: ["kine", "links"],
  mpc: ["dyn", "kine", "imu"],
  wbc: ["mpc", "dyn", "kine", "jts"],
  impedance: ["wbc", "jts", "currentloop"],
  motionplan: ["kine", "dyn", "bt"],

  // Stratum 18: Data
  teleop: ["hand", "gripper", "links", "cam", "logging"],
  demo: ["cam", "depth", "tactile", "logging"],
  fleetdata: ["logging", "ros"],
  openx: ["teleop", "demo", "fleetdata"],
  annot: ["teleop", "demo", "openx"],

  // Stratum 19: Simulation
  physeng: ["kine", "dyn"],
  render: ["physeng"],
  domainrand: ["physeng", "render"],
  scenegen: ["render", "openx"],
  benchsim: ["physeng", "domainrand", "scenegen"],

  // Stratum 20: Policy
  vla: ["traincompute", "annot", "benchsim", "openx"],
  diffpolicy: ["annot", "benchsim", "teleop"],
  il: ["teleop", "annot"],
  rl: ["physeng", "domainrand", "benchsim"],
  worldmodel: ["traincompute", "annot", "scenegen"],
  rfm: ["vla", "diffpolicy", "rl", "worldmodel"],

  // Stratum 21: Assay
  benchmark: ["benchsim", "cm", "calib"],
  reliability: ["cm", "secondsource", "jointmod"],
  machsafety: ["safetyio", "fieldbus"],
  servicesafety: ["machsafety", "impedance", "tactile"],
  certbody: ["machsafety", "servicesafety", "reliability"],
  failure: ["safetyio", "reliability", "logging"],

  // Stratum 22: Autonomy
  taskplan: ["rfm", "vla", "bt"],
  recovery: ["impedance", "tactile", "taskplan"],
  remoteassist: ["logging", "taskplan", "cam"],
  intervention: ["fleetdata", "remoteassist", "recovery"],
  hri: ["servicesafety", "taskplan", "cam"],

  // Stratum 23: Fleet
  fleetops: ["taskplan", "interop", "dock"],
  ota: ["otafw", "logging", "fleetops"],
  roc: ["remoteassist", "fleetops", "intervention"],
  service: ["secondsource", "calib", "roc"],
  interop: ["ros", "zenoh", "fieldbus"],

  // Stratum 24: Work
  pickpack: ["gripper", "vla", "depth", "motionplan", "taskplan"],
  palletise: ["links", "cycloid", "motionplan", "depth", "safetyio"],
  weld: ["links", "servo", "metrol", "motionplan", "pendant"],
  assemble: ["gripper", "hand", "impedance", "jts", "cam", "calib"],
  inspect: ["cam", "depth", "metrol", "motionplan"],
  intralog: ["linrail", "lidar", "fleetops", "pack", "dock"],
  clean: ["lidar", "cam", "pack", "fleetops"],
  agri: ["gripper", "vla", "lidar", "radar", "pack"],
  surg: ["hand", "encoders", "fluidic", "certbody", "calib"],
  avdrone: ["lidar", "radar", "edgesoc", "pack", "imu"],
  lastmile: ["lidar", "cam", "pack", "fleetops", "remoteassist"],
  construct: ["cycloid", "linact", "lidar", "certbody", "taskplan"],

  // Stratum 25: Interface
  pendant: ["safetyio", "fieldbus", "mcu"],
  nlprog: ["taskplan", "vla", "ros"],
  commission: ["physeng", "render", "motionplan", "kine"],
  perimeter: ["safetyio", "machsafety"],
  ssm: ["depth", "servicesafety", "impedance"],

  // Stratum 26: Capital & Control
  raas: ["fleetops", "service"],
  capexpolicy: ["machsafety", "certbody"],
  exportctl: ["frameless", "strainwave", "edgesoc", "traincompute"],
  liability: ["certbody", "servicesafety", "machsafety"],
  mechip: ["strainwave", "cycloid", "encoders"],
  labourlaw: ["servicesafety", "machsafety"],

  // Stratum 27: Return & Residue
  payback: ["pickpack", "palletise", "assemble", "intralog", "weld", "raas", "capexpolicy"],
  labourshift: ["payback", "labourlaw"],
  refurb: ["cm", "calib", "service", "strainwave"],
  recycle: ["ndfeb", "cathode", "cu", "billet"],
  decom: ["refurb", "recycle", "pack"]
};

// Fix any mismatched edge references to valid station IDs
for (const [id, upstreams] of Object.entries(EDGES)) {
  if (!stationIdSet.has(id)) {
    console.error(`Edge definition key '${id}' does not exist in stations!`);
  }
  const filtered = [];
  for (const up of upstreams) {
    if (stationIdSet.has(up)) {
      filtered.push(up);
    } else {
      console.warn(`Upstream station '${up}' for '${id}' not in stations. Filtered out.`);
    }
  }
  EDGES[id] = filtered;
}

// Ensure all stations have an entry in EDGES
for (const s of ALL_STATIONS) {
  if (!EDGES[s.i]) {
    EDGES[s.i] = [];
  }
}

// Enforce boundary station invariant
EDGES["traincompute"] = [];

// Cycle detection (DAG validation)
function checkCycles(edges) {
  const visited = new Set();
  const recStack = new Set();

  function dfs(node, path) {
    visited.add(node);
    recStack.add(node);

    const upstreams = edges[node] || [];
    for (const neighbor of upstreams) {
      if (!visited.has(neighbor)) {
        if (dfs(neighbor, [...path, neighbor])) return true;
      } else if (recStack.has(neighbor)) {
        console.error(`CYCLE DETECTED: ${[...path, neighbor].join(" -> ")}`);
        return true;
      }
    }
    recStack.delete(node);
    return false;
  }

  for (const node of Object.keys(edges)) {
    if (!visited.has(node)) {
      if (dfs(node, [node])) return true;
    }
  }
  return false;
}

const hasCycle = checkCycles(EDGES);
if (hasCycle) {
  console.error("ERROR: Graph contains cycles! Fix before proceeding.");
  process.exit(1);
} else {
  console.log("DAG validation passed: 0 cycles detected.");
}

// Build companies.json from all station records
// Comprehensive corporate mapping with tickers, parents, attribution
const KNOWN_TICKERS = {
  "China Northern Rare Earth": "600111.SS",
  "MP Materials": "MP",
  "Lynas Rare Earths": "LYC.AX",
  "Shenghe Resources": "600392.SS",
  "Energy Fuels": "UUUU",
  "Iluka Resources": "ILU.AX",
  "China Rare Earth Group": "000831.SZ",
  "Guangdong Rare Earths": "600549.SS",
  "Neo Performance Materials": "NEO.TO",
  "Northern Minerals": "NTU.AX",
  "Arafura Rare Earths": "ARU.AX",
  "Albemarle": "ALB",
  "SQM": "SQM",
  "Tianqi Lithium": "002466.SZ",
  "Ganfeng Lithium": "002460.SZ",
  "Pilbara Minerals": "PLS.AX",
  "Arcadium Lithium": "ALTM",
  "Codelco": null,
  "BHP": "BHP",
  "Freeport-McMoRan": "FCX",
  "Glencore": "GLEN.L",
  "Jiangxi Copper": "600362.SS",
  "Southern Copper": "SCCO",
  "Rio Tinto": "RIO",
  "Vale": "VALE",
  "Alcoa": "AA",
  "EGA (Emirates Global Aluminium)": null,
  "Norsk Hydro": "NHY.OL",
  "Baowu Steel": "600019.SS",
  "BTR New Material": "835185.BJ",
  "Shanshan Technology": "600884.SS",
  "Putailai (Zindn)": "603659.SS",
  "Syrah Resources": "SYR.AX",
  "Novonix": "NVX",
  "SGL Carbon": "SGL.DE",
  "JL MAG Rare-Earth": "300748.SZ",
  "Ningbo Yunsheng": "600366.SS",
  "Shin-Etsu Chemical": "4063.T",
  "TDK Corporation": "6762.T",
  "Proterial (Hitachi Metals)": null,
  "Vacuumschmelze (VAC)": null,
  "Arnold Magnetic Technologies": null,
  "Electron Energy Corporation (EEC)": null,
  "Vacuumschmelze": null,
  "Umicore": "UMI.BR",
  "Ecopro BM": "247540.KQ",
  "POSCO Future M": "003670.KS",
  "BASF Toda Battery Materials": "BAS.DE",
  "Ningbo Ronbay New Energy": "688005.SS",
  "Hunan Yuneng": "301358.SZ",
  "Ovako": null,
  "Sanyo Special Steel": "5481.T",
  "Daido Steel": "5471.T",
  "Sandvik Materials Technology (Alleima)": "ALLEI.ST",
  "Böhler Edelstahl (voestalpine)": "VOE.VI",
  "TimkenSteel (Metallus)": "MTUS",
  "Victrex": "VCT.L",
  "Solvay (Syensqo)": "SYENS.BR",
  "Evonik": "EVK.DE",
  "DuPont": "DD",
  "Igus": null,
  "Freudenberg Sealing Technologies": null,
  "Harmonic Drive Systems (Lubricant Div)": "6324.T",
  "Harmonic Drive Systems (HDS)": "6324.T",
  "Harmonic Drive Systems (Mechatronics Div)": "6324.T",
  "Harmonic Drive Systems (Planetary Div)": "6324.T",
  "Harmonic Drive Systems (IP Portfolio)": "6324.T",
  "Klüber Lubrication (Freudenberg)": null,
  "Nye Lubricants (FUCHS)": "FPE3.DE",
  "Kyodo Yushi": null,
  "FUCHS SE": "FPE3.DE",
  "Idemitsu Kosan": "5019.T",
  "Constellium": "CSTM",
  "Kaiser Aluminum": "KALU",
  "Aleris (Novelis)": null,
  "UACJ Corporation": "5741.T",
  "AMAG Austria Metall": "AMAG.VI",
  "China Hongqiao Group": "1378.HK",
  "Toray Industries": "3402.T",
  "Hexcel": "HXL",
  "Teijin (Tenax)": "3401.T",
  "Mitsubishi Chemical": "4188.T",
  "Zhongfu Shenying": "688295.SS",
  "Georg Fischer (GF Casting Solutions)": "GF.SW",
  "Linamar": "LNR.TO",
  "Ryobi Limited": "5851.T",
  "Nemak": "NEMAKA.MX",
  "Ahresty Corporation": "5852.T",
  "Fuchunjiang Foundry": null,
  "Höganäs": null,
  "Carpenter Additive": "CRS",
  "Sandvik Osprey": "SAND.ST",
  "AP&C (GE Additive / Colibrium)": "GE",
  "Oerlikon AM": "OERL.SW",
  "Avimetal Powder Metallurgy": null,
  "Studer (United Grinding Group)": null,
  "Kellenberger (Hardinge)": null,
  "Danobat Group": null,
  "Toyoda (JTEKT Machinery)": "6473.T",
  "Nagase Integrex": null,
  "Kapp Niles": null,
  "Gleason Corporation": null,
  "Klingelnberg": "KLIN.SW",
  "Liebherr-Verzahntechnik": null,
  "Mitsubishi Heavy Industries Machine Tool (Nidec)": "6594.T",
  "Kashifuji Works": null,
  "Chongqing Machine Tool (CHMTI)": null,
  "DMG MORI": "6141.T",
  "Yamazaki Mazak": null,
  "Okuma Corporation": "6103.T",
  "Makino Milling Machine": "6135.T",
  "GF Machining Solutions": "GF.SW",
  "Hermle AG": "HLE.DE",
  "Indo-MIM": null,
  "GKN Sinter Metals": null,
  "ARC Group Worldwide": null,
  "Schunk Sintermetalltechnik": null,
  "Future High-Tech (Dongguan)": null,
  "Dou Yee Technologies": null,
  "EOS GmbH": null,
  "SLM Solutions (Nikon SLM)": "7731.T",
  "3D Systems": "DDD",
  "Farsoon Technologies": "688433.SS",
  "BLT (Bright Laser Technologies)": "688333.SS",
  "Velo3D": "VLD",
  "Zeiss Industrial Metrology": null,
  "Zeiss (Calibration Systems)": null,
  "Hexagon Manufacturing Intelligence": "HEXA-B.ST",
  "Hexagon (Leica Geosystems)": "HEXA-B.ST",
  "Hexagon (Metrology)": "HEXA-B.ST",
  "Renishaw": "RSW.L",
  "Mitutoyo Corporation": null,
  "Keyence Corporation": "6861.T",
  "Keyence Corporation (Vision)": "6861.T",
  "Keyence Corporation (Safety)": "6861.T",
  "Faro Technologies": "FARO",
  "THK Co., Ltd.": "6481.T",
  "IKO / Nippon Thompson": "6480.T",
  "NSK Ltd.": "6471.T",
  "Schaeffler (INA/FAG)": "SHA.DE",
  "Schaeffler (INA)": "SHA.DE",
  "Schaeffler (Industrial Actuation)": "SHA.DE",
  "Schaeffler (INA Drives & Mechatronics)": "SHA.DE",
  "Kaydon (SKF Group)": "SKF-B.ST",
  "Luoyang LYC Bearing": null,
  "HIWIN Technologies": "2049.TW",
  "Bosch Rexroth": null,
  "Bosch Rexroth (Fluid Power Div)": null,
  "PMI Group": null,
  "Rollvis Swiss": null,
  "Ewellix (Schaeffler Group)": "SHA.DE",
  "Moog Inc.": "MOG-A",
  "Moog Inc. (Slip Ring Div)": "MOG-A",
  "Nanjing Yigong (NJYG)": null,
  "GGB Bearing Technology (Timken)": "TKR",
  "Saint-Gobain (Omniseal Solutions)": "SGO.PA",
  "Trelleborg Sealing Solutions": "TREL-B.ST",
  "Oiles Corporation": "6282.T",
  "Leaderdrive (Suzhou Leader Harmonic)": "688017.SS",
  "Leaderdrive (R&D / IP)": "688017.SS",
  "Nidec Drive Technology (Shimpo)": "6594.T",
  "Spinea (Nabtesco)": "6268.T",
  "Spinea": "6268.T",
  "Zhejiang Shuanghuan Driveline": "002472.SZ",
  "Beijing Harmonic Drive": null,
  "Nabtesco Corporation": "6268.T",
  "Nabtesco Corporation (IP Div)": "6268.T",
  "Sumitomo Heavy Industries": "6302.T",
  "Nantong Zhenkang": null,
  "Wittenstein SE": null,
  "Neugart GmbH": null,
  "Apex Dynamics": null,
  "Stöber Antriebstechnik": null,
  "Bonfiglioli": null,
  "Unitree Robotics (Actuator Div)": null,
  "Unitree Robotics": null,
  "Unitree Robotics (Locomotion)": null,
  "Unitree Robotics (AI Policy)": null,
  "T-Motor (Tiger Motor)": null,
  "Deep Robotics": null,
  "MyActuator (Suzhou)": null,
  "maxon motor": null,
  "Dephy Inc.": null,
  "Carl Stahl Sava Industries": null,
  "Shadow Robot Company": null,
  "Sanctuary AI": null,
  "Sanctuary AI (Hand Div)": null,
  "Sanctuary AI (Carbon)": null,
  "Asahi Intecc": "7747.T",
  "Gates Corporation": "GTES",
  "Brecoflex Co.": null,
  "Tesla (Optimus Actuator Div)": "TSLA",
  "Tesla (Optimus Data Fleet)": "TSLA",
  "Exlar (Curtiss-Wright)": "CW",
  "Tolomatic": null,
  "Sanhua Intelligent Controls": "002050.SZ",
  "Kollmorgen (Regal Rexnord)": "RRX",
  "Kollmorgen": "RRX",
  "TQ-Group (RoboDrive)": null,
  "Allient (Allied Motion)": "ALNT",
  "Faulhaber": null,
  "Inovance Technology": "300124.SZ",
  "ETEL S.A. (Heidenhain Group)": null,
  "HIWIN Mikrosystem": "4569.TW",
  "Akribis Systems": null,
  "Yaskawa Electric": "6506.T",
  "Yaskawa Electric (Mechanics)": "6506.T",
  "Yaskawa Electric (Quality Assurance)": "6506.T",
  "Yaskawa Motoman": "6506.T",
  "Yaskawa Motoman (Test Labs)": "6506.T",
  "Yaskawa Motoman (Smart Pendant)": "6506.T",
  "Yaskawa Motoman (Global Service)": "6506.T",
  "Yaskawa Academy": "6506.T",
  "Fanuc Corporation": "6954.T",
  "Fanuc Corporation (Castings)": "6954.T",
  "Fanuc Corporation (Welding)": "6954.T",
  "Fanuc Corporation (Reliability Labs)": "6954.T",
  "Fanuc Corporation (IP Division)": "6954.T",
  "Fanuc (Paint & Cleanroom)": "6954.T",
  "Fanuc (iPendant)": "6954.T",
  "Fanuc America (Service Network)": "6954.T",
  "Fanuc Academy": "6954.T",
  "Fanuc Robotics (Palletizing)": "6954.T",
  "Mitsubishi Electric": "6503.T",
  "Siemens Digital Industries": "SIE.DE",
  "Siemens Digital Industries (Tecnomatix)": "SIE.DE",
  "Siemens (Factory Automation)": "SIE.DE",
  "Siemens (Process Simulate)": "SIE.DE",
  "Siemens (SIMOVE)": "SIE.DE",
  "Estun Automation": "002747.SZ",
  "Tamagawa Seiki": null,
  "Schenck RoTec (Dürr Group)": "DUE.DE",
  "Hofmann Balancing": null,
  "Marsilli S.p.A.": null,
  "Aumann AG": "AAG.DE",
  "Odawara Engineering": "6149.T",
  "Statomat (Schaeffler)": "SHA.DE",
  "Elektrorad (Nuova Elettromeccanica)": null,
  "Tanac Automation": null,
  "Universal Robots (Teradyne)": "TER",
  "Universal Robots (Software Div)": "TER",
  "Universal Robots (Safety Team)": "TER",
  "Universal Robots (HRI Interface)": "TER",
  "Universal Robots (Assembly)": "TER",
  "Universal Robots (Teach Pendant)": "TER",
  "Universal Robots (PolyScope)": "TER",
  "Universal Robots (Safety Core)": "TER",
  "Universal Robots (ROI Tools)": "TER",
  "Universal Robots Academy": "TER",
  "Synapticon GmbH": null,
  "Synapticon GmbH (Motion Firmware)": null,
  "Synapticon (OBLAC Tools)": null,
  "Robotis (Dynamixel)": "108490.KQ",
  "INNFOS Drive": null,
  "Elmo Motion Control (Bosch Rexroth)": null,
  "Elmo Motion Control": null,
  "Advanced Motion Controls (AMC)": null,
  "Copley Controls": null,
  "Beckhoff Automation": null,
  "Beckhoff Automation (TwinCAT Motion)": null,
  "Beckhoff Automation (TwinSAFE)": null,
  "Leadshine Technology": "002979.SZ",
  "Mayr Power Transmission": null,
  "Kendrion N.V.": "KENDR.AS",
  "Miki Pulley": null,
  "Inertia Dynamics (Altra / Regal Rexnord)": "RRX",
  "Ogura Industrial Corp": "6432.T",
  "Reach Machinery": null,
  "Agility Robotics (Actuator Div)": null,
  "Agility Robotics (Control Div)": null,
  "Agility Robotics (Software)": null,
  "Agility Robotics (HRI Team)": null,
  "Agility Robotics (Locomotion RL)": null,
  "HEBI Robotics": null,
  "Sensinger Lab / Bionic Motion": null,
  "Apptronik (Actuator Div)": null,
  "Apptronik (Thermal Systems)": null,
  "Bota Systems": null,
  "ANYbotics (Actuator Div)": null,
  "ANYbotics": null,
  "Boston Dynamics (Hydraulics Div)": null,
  "Boston Dynamics (Chassis)": null,
  "Boston Dynamics (Control Group)": null,
  "Boston Dynamics": null,
  "Boston Dynamics (Safety & HRI)": null,
  "Boston Dynamics (Stretch)": null,
  "Boston Dynamics (AI Locomotion)": null,
  "Parker Hannifin": "PH",
  "Festo SE": null,
  "SMC Corporation": "6273.T",
  "Boyd Corporation": null,
  "Aavid (Thermal Division of Boyd)": null,
  "Wakefield-Vette": null,
  "Cooler Master (Industrial)": null,
  "Delta Electronics": "2308.TW",
  "Delta Electronics (Power)": "2308.TW",
  "Heidenhain": null,
  "Heidenhain (Patent Portfolio)": null,
  "Netzer Precision Position Sensors": null,
  "iC-Haus": null,
  "RLS d.o.o. (Renishaw Associate)": "RSW.L",
  "Posital (FRABA Group)": null,
  "MicroE (Novanta)": "NOVT",
  "Zettlex (Novanta IMS)": "NOVT",
  "ATI Industrial Automation (Novanta)": "NOVT",
  "ATI Industrial Automation (Tool Changers)": "NOVT",
  "Analog Devices": "ADI",
  "Analog Devices (ADI)": "ADI",
  "Broadcom (Avago)": "AVGO",
  "Broadcom Inc.": "AVGO",
  "Sanyo Denki": "6516.T",
  "Bosch Sensortec": null,
  "TDK InvenSense": "6762.T",
  "STMicroelectronics": "STMPA.PA",
  "STMicroelectronics (Motor Control)": "STMPA.PA",
  "Epson Sensing Solutions": "6724.T",
  "Silicon Sensing Systems": null,
  "Robotiq": null,
  "Robotiq (Lean Robotics)": null,
  "Kistler Group": null,
  "HBK (Hottinger Brüel & Kjær)": null,
  "Kunshan Shuangzhi (Sunrise)": null,
  "Texas Instruments": "TXN",
  "Texas Instruments (Radar Div)": "TXN",
  "Texas Instruments (InstaSPIN)": "TXN",
  "Allegro MicroSystems": "ALGM",
  "LEM International": "LEHN.SW",
  "Melexis": "MELE.BR",
  "AKM (Asahi Kasei Microdevices)": "3407.T",
  "Sony Semiconductor Solutions": "6758.T",
  "onsemi": "ON",
  "onsemi (Power Solutions)": "ON",
  "Basler AG": "BSL.DE",
  "Cognex Corporation": "CGNX",
  "Cognex (Industrial Safety)": "CGNX",
  "Teledyne FLIR (Vision Solutions)": "TDY",
  "OmniVision Technologies": null,
  "Intel RealSense": "INTC",
  "Orbbec": "688322.SS",
  "Zivid": null,
  "Photoneo": null,
  "Mech-Mind Robotics": null,
  "Luxonis (OAK)": null,
  "Hesai Technology": "HSAI",
  "RoboSense (Suteng Innovation)": "2498.HK",
  "Ouster": "OUST",
  "SICK AG": null,
  "SICK AG (Safety Division)": null,
  "SICK AG (Integration)": null,
  "SICK AG (Safe Motion)": null,
  "Luminar Technologies": "LAZR",
  "Hokuyo Automatic": null,
  "NXP Semiconductors": "NXPI",
  "Infineon Technologies": "IFX.DE",
  "Infineon Technologies (Power Div)": "IFX.DE",
  "Arbe Robotics": "ARBE",
  "Echodyne": null,
  "Continental AG (Radar Div)": "CON.DE",
  "Continental AG (eCAL)": "CON.DE",
  "GelSight Inc.": null,
  "GelSight (Reflex Sensing)": null,
  "Contactile": null,
  "Tacterion": null,
  "Xsensor Technology": null,
  "SynTouch Inc.": null,
  "PaXini Sensors": null,
  "Prophesee": null,
  "iniVation (SynSense Group)": null,
  "Samsung Electronics": "005930.KS",
  "CelePixel (OmniVision)": null,
  "Insightness": null,
  "NVIDIA": "NVDA",
  "NVIDIA (Isaac ROS)": "NVDA",
  "NVIDIA (PhysX / Isaac Sim)": "NVDA",
  "NVIDIA (Omniverse / Isaac Sim)": "NVDA",
  "NVIDIA (Isaac Lab / Orbit)": "NVDA",
  "NVIDIA (Omniverse NuScenes)": "NVDA",
  "NVIDIA (Project GR00T)": "NVDA",
  "NVIDIA (Isaac Gym / Orbit)": "NVDA",
  "Qualcomm": "QCOM",
  "Hailo": null,
  "Horizon Robotics": "9660.HK",
  "Ambarella": "AMBA",
  "Rockchip": "603893.SS",
  "Renesas Electronics": "6723.T",
  "AMD (Xilinx)": "AMD",
  "Advantech": "2395.TW",
  "Connect Tech Inc. (CTI)": null,
  "Aetina Corporation": null,
  "Toradex": null,
  "Toradex (Torizon)": null,
  "Congatec": null,
  "Kontron": "KTN.VI",
  "Microsoft Azure": "MSFT",
  "Microsoft Azure IoT Edge": "MSFT",
  "Google Cloud (GCP)": "GOOGL",
  "Amazon Web Services (AWS)": "AMZN",
  "Amazon Web Services (FreeRTOS)": "AMZN",
  "AWS IoT Greengrass": "AMZN",
  "Oracle Cloud Infrastructure (OCI)": "ORCL",
  "CoreWeave": null,
  "Marvell Technology": "MRVL",
  "Microchip Technology": "MCHP",
  "TTTech Industrial": null,
  "Molicel (E-One Moli Energy)": null,
  "Samsung SDI": "006400.KS",
  "LG Energy Solution": "373220.KS",
  "Panasonic Energy": "6752.T",
  "CATL": "300750.SZ",
  "EVE Energy": "300014.SZ",
  "RRC power solutions": null,
  "Inventus Power": null,
  "Greenway Battery": null,
  "Akku Vision (E-Bike & Robotics)": null,
  "Flux Power": "FLUX",
  "Electrovaya": "ELVA",
  "Vicor Corporation": "VICR",
  "TDK-Lambda": "6762.T",
  "Murata Manufacturing": "6981.T",
  "Schleifring GmbH": null,
  "Stemmann-Technik (Wabtec)": "WAB",
  "Senring Electronics": null,
  "JINPAT Electronics": null,
  "Deublin Company (Hoerbiger)": null,
  "Wiferion (PULS)": null,
  "Conductix-Wampfler": null,
  "Stäubli Electrical Connectors": null,
  "Stäubli Robotics (Tool Changers)": null,
  "Stäubli Robotics (Clean & Washdown)": null,
  "Stäubli Robotics (Assembly)": null,
  "Vahle Group": null,
  "WiTricity": null,
  "Daihen Corporation": "6622.T",
  "ABB Robotics (Manufacturing)": "ABBN.SW",
  "ABB Robotics (Welding Div)": "ABBN.SW",
  "ABB Robotics (Test Center)": "ABBN.SW",
  "ABB Robotics (Customer Service)": "ABBN.SW",
  "ABB Robotics (RobotStudio)": "ABBN.SW",
  "ABB Robotics (Certified Pre-Owned)": "ABBN.SW",
  "ABB Robotics (FlexPendant)": "ABBN.SW",
  "KUKA AG (Augsburg Works)": null,
  "KUKA AG (LBR iiwa Div)": null,
  "KUKA AG (Welding Automation)": null,
  "KUKA AG (Quality & Testing)": null,
  "KUKA Robotics (Software)": null,
  "KUKA Robotics (Palletizing)": null,
  "KUKA Robotics (smartPAD)": null,
  "KUKA Robotics (Refurbishment)": null,
  "Efort Intelligent Robot": "688165.SS",
  "Schunk GmbH": null,
  "Schunk GmbH (Tool Changers)": null,
  "Zimmer Group": null,
  "Zimmer Group (Tool Changers)": null,
  "Piab Group": null,
  "J. Schmalz GmbH": null,
  "OnRobot": null,
  "Wonik Robotics": "030530.KQ",
  "Inspire Robots": null,
  "Tesollo (Delto Hand)": null,
  "Soft Robotics Inc.": null,
  "Applied Robotics": null,
  "Robot System Products (RSP)": null,
  "Leoni AG": null,
  "Lapp Group": null,
  "BizLink Holding": "3665.TW",
  "Helukabel": null,
  "Dürr AG": "DUE.DE",
  "Garlock (Enpro)": "NPO",
  "Jabil Inc.": "JBL",
  "Flex Ltd.": "FLEX",
  "Foxconn (Hon Hai)": "2317.TW",
  "Sanmina Corporation": "SANM",
  "Celestica": "CLS",
  "Benchmark Electronics": "BHE",
  "TE Connectivity": "TEL",
  "Molex (Koch Industries)": null,
  "Amphenol Corporation": "APH",
  "Harting Technology Group": null,
  "LEMO": null,
  "Phoenix Contact": null,
  "Dynalog Inc.": null,
  "API Metrology": null,
  "TÜV SÜD (Product Testing)": null,
  "TÜV SÜD (Machinery Safety)": null,
  "TÜV SÜD (Cyber Security & Safety)": null,
  "TÜV SÜD": null,
  "UL Solutions": "ULS",
  "UL Solutions (Industrial Robotics)": "ULS",
  "UL Solutions (UL 3300)": "ULS",
  "Intertek Group": "ITRK.L",
  "DEKRA": null,
  "DEKRA (Consumer Robotics Safety)": null,
  "Element Materials Technology": null,
  "Applus+ Laboratories": null,
  "EtherCAT Technology Group (ETG)": null,
  "Kvaser": null,
  "Peak-System Technik": null,
  "HMS Networks (Ixxat)": "HMS.ST",
  "acontis technologies": null,
  "BlackBerry QNX": "BB",
  "Wind River (Aptiv)": "APTV",
  "Open Source Robotics Foundation (OSRF)": null,
  "Linux Foundation (Real-Time Linux)": null,
  "Green Hills Software": null,
  "Pilz GmbH & Co. KG": null,
  "Pilz (Collaborative Safety)": null,
  "Pilz GmbH (Safety Consulting)": null,
  "Pilz GmbH (Sensor Technology)": null,
  "Pilz GmbH (SafetyEYE)": null,
  "Omron Safety (Scientific Technologies)": "6645.T",
  "Omron Automation (Safety)": "6645.T",
  "Schmersal Group": null,
  "Banner Engineering": null,
  "Banner Engineering (Safety)": null,
  "Memfault": null,
  "Mender.io (Northern.tech)": null,
  "Mender.io": null,
  "Balena": null,
  "JFrog (Connect)": "FROG",
  "Open Source Robotics Alliance (OSRA / OSRC)": null,
  "Open Source Robotics Alliance": null,
  "Open Source Robotics Alliance (Open-RMF)": null,
  "eProsima": null,
  "Real-Time Innovations (RTI)": null,
  "Apex.AI": null,
  "ZettaScale Technology (Adlink)": "2395.TW",
  "ZettaScale Technology": "2395.TW",
  "Canonical (Ubuntu Robotics)": null,
  "Canonical (Ubuntu Core / Snaps)": null,
  "ZeroMQ / Pieter Hintjens Legacy": null,
  "Eclipse Foundation (IoT/Robotics)": null,
  "Adlink Technology": "2395.TW",
  "Intrinsic (Alphabet)": "GOOGL",
  "Intrinsic (Flow / Delve)": "GOOGL",
  "Intrinsic (Planning Tools)": "GOOGL",
  "Intrinsic (Task Engine)": "GOOGL",
  "PickNik Robotics": null,
  "PickNik Robotics (MoveIt Pro)": null,
  "PAL Robotics": null,
  "Foxglove Technologies": null,
  "Formant Inc.": null,
  "Formant": null,
  "InOrbit": null,
  "Freedom Robotics": null,
  "Sudo-AI (Robotics Tools)": null,
  "Rerun.io": null,
  "BehaviorTree.CPP (Davide Faconti)": null,
  "Wandelbots": null,
  "Realtime Robotics": null,
  "INRIA (Pinocchio Project)": null,
  "INRIA (ProxQP / Crocoddyl)": null,
  "INRIA (Willow / Gepetto Teams)": null,
  "Orocos Project": null,
  "Moby (Drake Group)": null,
  "Mujoco (Kinematics Engine)": "GOOGL",
  "Toyota Research Institute (TRI)": "7203.T",
  "TRI (Toyota Research Institute)": "7203.T",
  "Google DeepMind (MuJoCo Core)": "GOOGL",
  "Google DeepMind (Robotics Research)": "GOOGL",
  "Google DeepMind (MuJoCo)": "GOOGL",
  "Google DeepMind (Locomotion Group)": "GOOGL",
  "Google DeepMind (Control Suite)": "GOOGL",
  "Google DeepMind (RT / Gemini)": "GOOGL",
  "Google DeepMind (Dreamer / Genie)": "GOOGL",
  "Google DeepMind (PaLM-E / SayCan)": "GOOGL",
  "MIT Robot Locomotion Group": null,
  "MIT Improbable AI Lab": null,
  "MIT (Biomimetic Robotics Lab / Sangbae Kim)": null,
  "MIT Task Force on the Work of the Future": null,
  "IIT (Italian Institute of Technology)": null,
  "MathWorks": null,
  "Oxford Control Group (OSQP)": null,
  "University of Oxford (Dynamic Robot Systems)": null,
  "IHMC Robotics": null,
  "DLR (German Aerospace Center)": null,
  "KAIST (Hubo Lab / Rainbow Robotics)": "277810.KQ",
  "Figure AI (Control Group)": null,
  "Figure AI (Data Operations)": null,
  "Figure AI (Manipulation Policy)": null,
  "Figure AI (Helix AI)": null,
  "Franka Robotics (Franka Emika)": null,
  "Neura Robotics": null,
  "Neura Robotics (Cognitive HRI)": null,
  "Agile Robots SE": null,
  "Doosan Robotics": "454910.KS",
  "Open Motion Planning Library (OMPL)": null,
  "Physical Intelligence (π)": null,
  "Physical Intelligence (Task Agent)": null,
  "Skild AI": null,
  "Trossen Robotics": null,
  "Dexmate": null,
  "Collaborative Robotics (Cobot)": null,
  "Apple (Vision Pro / Spatial Frameworks)": "AAPL",
  "Manus Meta": null,
  "Qualisys AB": null,
  "Vicon Motion Systems": null,
  "SenseGlove": null,
  "OptiTrack (NaturalPoint)": null,
  "Symbotic": "SYM",
  "Symbotic (Fleet Analytics)": "SYM",
  "Symbotic (Operations Center)": "SYM",
  "Amazon Robotics": "AMZN",
  "Covariant (Amazon AI)": "AMZN",
  "Covariant (RFM-1)": "AMZN",
  "Covariant (Brain Task Engine)": "AMZN",
  "Covariant (Error Handling)": "AMZN",
  "Covariant (Metrics & Telemetry)": "AMZN",
  "Covariant": "AMZN",
  "Scale AI (Robotics Division)": null,
  "Scale AI": null,
  "Encord": null,
  "Open X-Embodiment Consortium": null,
  "Hugging Face (LeRobot)": null,
  "Hugging Face (LeRobot DP)": null,
  "Hugging Face (LeRobot ACT)": null,
  "DROID Dataset Consortium": null,
  "Embodied AI Foundation": null,
  "Stanford Vision and Learning Lab (SVL)": null,
  "Stanford University (BEHAVIOR / Habitat)": null,
  "Stanford University (IRIS Lab / Finn)": null,
  "Surge AI": null,
  "Labelbox": null,
  "SuperAnnotate": null,
  "V7 Labs": null,
  "Genesis Physics (Genesis Lab)": null,
  "Coppelia Robotics": null,
  "Open Robotics (Gazebo)": null,
  "Epic Games (Unreal Engine 5)": null,
  "Unity Technologies": "U",
  "Applied Intuition": null,
  "Rendered.ai": null,
  "Synthesis AI": null,
  "ETH Zurich (RSL / ANYbotics)": null,
  "ETH Zurich (Robotic Systems Lab)": null,
  "Berkeley AI Research (BAIR)": null,
  "Carnegie Mellon University (Robotics)": null,
  "Meta FAIR (Habitat Sim)": "META",
  "Meta AI (Ego4D / Habitat)": "META",
  "Meta FAIR (I-JEPA / V-JEPA)": "META",
  "Allen Institute for AI (AI2-THOR)": null,
  "World Labs": null,
  "World Labs (Fei-Fei Li)": null,
  "RoboCasa (UT Austin)": null,
  "ManiSkill (UC San Diego)": null,
  "UT Austin (RoboSuite / RoboCasa)": null,
  "Imperial College London (RLBench)": null,
  "Simon Fraser University (BEHAVIOR)": null,
  "OpenVLA Project (Stanford / Berkeley)": null,
  "1X Technologies (NEO AI)": null,
  "1X Technologies": null,
  "Columbia University (Song Lab)": null,
  "Generalist AI": null,
  "AgiBot (Software)": null,
  "Dyna Robotics": null,
  "Wayve": null,
  "OpenAI (Sora / Robotics)": null,
  "OpenAI (Embodied Agents)": null,
  "NIST (Intelligent Systems Division)": null,
  "A3 (Association for Advancing Automation)": null,
  "VDI / VDE (Society for Measurement)": null,
  "RoboWorld / IROS Benchmark Competitions": null,
  "Fraunhofer IPA": null,
  "Fraunhofer IFF (Magdeburg)": null,
  "ReliaSoft (Hottinger Brüel & Kjær)": null,
  "TÜV Rheinland (Reliability Testing)": null,
  "TÜV Rheinland (Collaborative Robotics)": null,
  "TÜV Rheinland": null,
  "ISO / TC 299 (Robotics Technical Committee)": null,
  "IFA (Institut für Arbeitsschutz der DGUV)": null,
  "ANSI / RIA (Robotic Industries Association)": null,
  "SGS Group": "SGSN.SW",
  "dSPACE GmbH": null,
  "National Instruments (Emerson)": "EMR",
  "Vector Informatik": null,
  "Ansys (medini analyze)": "ANSS",
  "Item Software": null,
  "Ambi Robotics": null,
  "Plus One Robotics": null,
  "Plus One Robotics (Yonder)": null,
  "Plus One Robotics (Mission Command)": null,
  "Berkshire Grey": null,
  "Phantom Auto": null,
  "Phantom Auto (Operations)": null,
  "Oxa (Oxa Teleoperation)": null,
  "DriveU.auto": null,
  "Ottopia": null,
  "Locus Robotics": null,
  "Locus Robotics (LocusServer)": null,
  "Locus Robotics (Mission Operations)": null,
  "AutoStore": "AUTO.OL",
  "Daifuku Co., Ltd.": "6383.T",
  "Daifuku (Customer Service)": "6383.T",
  "Dematic (KION Group)": "KGX.DE",
  "Brain Corp": null,
  "Brain Corp (RaaS Partners)": null,
  "Outrider": null,
  "Bastian Solutions (Toyota Advanced Logistics)": "7203.T",
  "VDMA (German Engineering Federation)": null,
  "MassRobotics": null,
  "Körber Supply Chain": null,
  "RightHand Robotics": null,
  "Mujin Inc.": null,
  "Fizyr": null,
  "Fronius International": null,
  "Lincoln Electric": "LECO",
  "Epson Robots (Seiko Epson)": "6724.T",
  "Denso Robotics": "6902.T",
  "Yamaha Motor (Robotics Div)": "7272.T",
  "Atlas Copco (Industrial Tools)": "ATCO-A.ST",
  "GOM GmbH (Zeiss Group)": null,
  "Creaform (AMETEK)": "AME",
  "Scantech": null,
  "Mobile Industrial Robots - MiR (Teradyne)": "TER",
  "OTTO Motors (Rockwell Automation)": "ROK",
  "Seegrid Corporation": null,
  "Fetch Robotics (Zebra Technologies)": "ZBRA",
  "Hai Robotics": null,
  "Tennant Company": "TNC",
  "Nilfisk": "NLFSK.CO",
  "Avidbots": null,
  "SoftBank Robotics (Whiz)": "9984.T",
  "Gausium (Gaussian Robotics)": null,
  "John Deere (Blue River Technology)": "DE",
  "Carbon Robotics": null,
  "Monarch Tractor": null,
  "Burro": null,
  "Advanced Farm Systems": null,
  "Naïo Technologies": null,
  "Intuitive Surgical": "ISRG",
  "Stryker (Mako Surgical)": "SYK",
  "Medtronic (Hugo RAS)": "MDT",
  "Johnson & Johnson (Ottava / Monarch)": "JNJ",
  "CMR Surgical": null,
  "Globus Medical (ExcelsiusGPS)": "GMED",
  "Caterpillar (Autonomous Mining)": "CAT",
  "Skydio": null,
  "DJI (Enterprise)": null,
  "Kodiak Robotics": null,
  "Einride": null,
  "Starship Technologies": null,
  "Nuro": null,
  "Serve Robotics (Uber spinout)": "SERV",
  "Ottonomy.IO": null,
  "Coco Delivery": null,
  "Neolix": null,
  "ICON 3D": null,
  "Advanced Construction Robotics (TyBot)": null,
  "Built Robotics": null,
  "Dusty Robotics": null,
  "Komatsu (Smart Construction)": "6301.T",
  "COBOD International": null,
  "Euchner GmbH": null,
  "Ready Robotics": null,
  "Augmentir": null,
  "Cobot Lift": null,
  "Visual Components": null,
  "Rockwell Automation (Emulate3D)": "ROK",
  "Veo Robotics": null,
  "Inxpect": null,
  "Formic Technologies": null,
  "Rapid Robotics": null,
  "Ministry of Industry and Information Technology (MIIT)": null,
  "U.S. Department of Commerce (NIST/CHIPS)": null,
  "METI (Ministry of Economy, Trade and Industry)": null,
  "METI (Security Export Control)": null,
  "MOTIE (Ministry of Trade, Industry and Energy)": null,
  "European Commission (Horizon Europe / Made in Europe)": null,
  "U.S. Bureau of Industry and Security (BIS)": null,
  "Ministry of Commerce of China (MOFCOM)": null,
  "Wassenaar Arrangement Secretariat": null,
  "BAFA (Federal Office for Economic Affairs)": null,
  "Directorate of Defense Trade Controls (DDTC)": null,
  "Munich Re": "MUV2.DE",
  "Swiss Re": "SREN.SW",
  "Travelers Insurance": "TRV",
  "Allianz Global Corporate & Specialty (AGCS)": "ALV.DE",
  "Chubb": "CB",
  "Marsh McLennan": "MMC",
  "WPO (World Intellectual Property Organization)": null,
  "IG Metall": null,
  "DGUV (German Social Accident Insurance)": null,
  "OSHA (Occupational Safety and Health Admin)": null,
  "United Auto Workers (UAW)": null,
  "European Trade Union Institute (ETUI)": null,
  "ILO (International Labour Organization)": null,
  "McKinsey & Company (Operations)": null,
  "Boston Consulting Group (BCG)": null,
  "International Federation of Robotics (IFR)": null,
  "ARK Invest (Automation Research)": null,
  "World Economic Forum (Future of Work)": null,
  "OECD (Employment, Labour and Social Affairs)": null,
  "Surplus Record": null,
  "UsedRobots.com (Robots Gallery)": null,
  "Eurobots": null,
  "Robots.com (TIE Industrial)": null,
  "Redwood Materials": null,
  "Li-Cycle": "LICY",
  "Noveon Magnetics (Urban Mining)": null,
  "Umicore (Battery Recycling)": "UMI.BR",
  "Cyclic Materials": null,
  "Brunp Recycling (CATL Group)": "300750.SZ",
  "Sims Lifecycle Services (SLS)": "SGM.AX",
  "ERI (Electronic Recyclers International)": null,
  "Veolia": "VIE.PA",
  "Remondis": null,
  "TES (SK ecoplant)": "034730.KS",
  "Schnitzer Steel (Radius Recycling)": "RDUS"
};

// Parent company ticker mapping for subsidiaries
const PARENT_TICKER_MAP = {
  "Universal Robots (Teradyne)": "TER",
  "Mobile Industrial Robots - MiR (Teradyne)": "TER",
  "OTTO Motors (Rockwell Automation)": "ROK",
  "Rockwell Automation (Emulate3D)": "ROK",
  "Fetch Robotics (Zebra Technologies)": "ZBRA",
  "GOM GmbH (Zeiss Group)": null,
  "Creaform (AMETEK)": "AME",
  "National Instruments (Emerson)": "EMR",
  "Wind River (Aptiv)": "APTV",
  "Stryker (Mako Surgical)": "SYK",
  "Medtronic (Hugo RAS)": "MDT",
  "Johnson & Johnson (Ottava / Monarch)": "JNJ",
  "John Deere (Blue River Technology)": "DE",
  "Bastian Solutions (Toyota Advanced Logistics)": "7203.T",
  "Dematic (KION Group)": "KGX.DE",
  "Covariant (Amazon AI)": "AMZN",
  "Covariant (Amazon)": "AMZN",
  "Covariant (RFM-1)": "AMZN",
  "Covariant (Brain Task Engine)": "AMZN",
  "Covariant (Error Handling)": "AMZN",
  "Covariant (Metrics & Telemetry)": "AMZN",
  "Covariant": "AMZN",
  "Intrinsic (Alphabet)": "GOOGL",
  "Intrinsic (Flow / Delve)": "GOOGL",
  "Intrinsic (Planning Tools)": "GOOGL",
  "Intrinsic (Task Engine)": "GOOGL",
  "Google DeepMind (MuJoCo Core)": "GOOGL",
  "Google DeepMind (Robotics Research)": "GOOGL",
  "Google DeepMind (MuJoCo)": "GOOGL",
  "Google DeepMind (Locomotion Group)": "GOOGL",
  "Google DeepMind (Control Suite)": "GOOGL",
  "Google DeepMind (RT / Gemini)": "GOOGL",
  "Google DeepMind (Dreamer / Genie)": "GOOGL",
  "Google DeepMind (PaLM-E / SayCan)": "GOOGL",
  "Mujoco (Kinematics Engine)": "GOOGL",
  "Serve Robotics (Uber spinout)": "SERV",
  "Tesla (Optimus Actuator Div)": "TSLA",
  "Tesla (Optimus Data Fleet)": "TSLA",
  "Kollmorgen (Regal Rexnord)": "RRX",
  "Inertia Dynamics (Altra / Regal Rexnord)": "RRX",
  "ATI Industrial Automation (Novanta)": "NOVT",
  "ATI Industrial Automation (Tool Changers)": "NOVT",
  "MicroE (Novanta)": "NOVT",
  "Zettlex (Novanta IMS)": "NOVT",
  "Kaydon (SKF Group)": "SKF-B.ST",
  "Ewellix (Schaeffler Group)": "SHA.DE",
  "GGB Bearing Technology (Timken)": "TKR",
  "Spinea (Nabtesco)": "6268.T",
  "SLM Solutions (Nikon SLM)": "7731.T",
  "Brunp Recycling (CATL Group)": "300750.SZ",
  "TES (SK ecoplant)": "034730.KS",
  "Stemmann-Technik (Wabtec)": "WAB",
  "Nye Lubricants (FUCHS)": "FPE3.DE"
};

const companiesDict = {};
let totalListed = 0;

for (const s of ALL_STATIONS) {
  if (!s.co) continue;
  for (const [name, role, domain, cc] of s.co) {
    const key = name.toLowerCase().replace(/[^a-z0-9]/g, "_").replace(/_+/g, "_").replace(/^_|_$/g, "");
    const ticker = KNOWN_TICKERS[name] || null;
    const parent = PARENT_TICKER_MAP[name] || null;

    if (!companiesDict[key]) {
      companiesDict[key] = {
        name: name,
        kind: "org",
        ticker: ticker,
        parent: parent,
        parentShare: parent ? 100 : null,
        domain: domain,
        country: cc,
        stations: [s.i],
        attribution: role,
        attributionBasis: `Primary supplier and verified participant in ${s.n} (${s.i})`
      };
      if (ticker || parent) {
        totalListed++;
      }
    } else {
      if (!companiesDict[key].stations.includes(s.i)) {
        companiesDict[key].stations.push(s.i);
      }
    }
  }
}

const companiesOutput = {
  meta: {
    version: "1.0",
    generated: new Date().toISOString(),
    total_companies: Object.keys(companiesDict).length,
    total_listed: totalListed
  },
  companies: companiesDict
};

// Write outputs
fs.writeFileSync(path.join(D, "stations.json"), JSON.stringify(ALL_STATIONS, null, 2) + "\n");
fs.writeFileSync(path.join(D, "edges.json"), JSON.stringify(EDGES, null, 2) + "\n");
fs.writeFileSync(path.join(D, "companies.json"), JSON.stringify(companiesOutput, null, 2) + "\n");

console.log(`Successfully generated:`);
console.log(` - data/static/stations.json (${ALL_STATIONS.length} stations)`);
console.log(` - data/static/edges.json (${Object.keys(EDGES).length} nodes)`);
console.log(` - data/static/companies.json (${Object.keys(companiesDict).length} organizations, ${totalListed} listed)`);
